apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-api.fullname" . }}
  labels:
    {{- include "node-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: api-web
      port: {{ .Values.service.port }}
      targetPort: api-web
      protocol: TCP
  selector:
    {{- include "node-api.selectorLabels" . | nindent 4 }}
